### PR TITLE
Fix issue 25

### LINKED ISSUE #25: ksuid.Parse sometimes panics instead of returning an error
When parsing a 27-long string that is not a valid ksuid, it will panic instead of returning an error. For instance `ksuid.Parse("aaaaaaaaaaaaaaaaaaaaaaaaaaa")` will panic.

The signature `func Parse(s string) (KSUID, error)` seems to imply that any string that can't successfully be parsed should return an error, and not panic. I think that should be the expected behavior at least.

Maybe the fix would be to update `Parse` or `fastDecodeBase62` to not panic? In any case, if there's a valid reason for wanting it to panic, the documentation should be updated so it doesn't come as a surprise.

### PR DESCRIPTION
**Pull request by achille-roussel**
Fixes #25 

This PR changes the fastDecodeBase62 implementation to prevent out-of-bounds errors when invalid KSUIDs are decoded.

### CODE REVIEW

File: ksuid.go [hunk 1]
```diff
@@ -179,7 +183,11 @@ func Parse(s string) (KSUID, error) {
 	dst := [byteLength]byte{}
 
 	copy(src[:], s[:])
-	fastDecodeBase62(dst[:], src[:])
+
+	if err := fastDecodeBase62(dst[:], src[:]); err != nil {
+		return Nil, errStrValue
```
Comment (f2prateek) [inline ksuid.go]: This seems slightly leaky. Would `fastDecodeBase62` never error for a reason other than `errStrValue`? The current implementation wouldn't, but is that ok to assume for the future?

Comment (achille-roussel) [reply ksuid.go]: I think it's fine, there's little chance for this code to change, plus it's an implementation detail so we're free to change it if needed be.

**Comment by achille-roussel** [comment]
Thanks for the review, you're right about CI we should add this sometimes.
